### ISSUE TITLE
invalid memory address or nil pointer dereference error retrieving resources (Same as #257??)

### ISSUE THREAD

**Issue by farreciado** [Azure/aztfy#282]
In one of my subscriptions I found this exception. The subscription is in another tenant I've been granted as Contributor. After some seconds trying to list resources in a RG, an exception is thrown:

panic: runtime error: invalid memory address or nil pointer dereference
                                                                       [signal 0xc0000005 code=0x0 addr=0x0 pc=0xb5bdd8]

                                                                                                                        goroutine 290 [running]:
                                                                                                                                                github.com/magodo/azlist/azlist.listDirectChildResource({0x2027080, 0x1390209c}, 0x1404b048, 0x14266360, {{0x2028ec4, 0x14056300}, 0x13fb0d20})
                                                                                                                                                github.com/magodo/azlist@v0.0.0-20220923015326-17b16cc9b805/azlist/azlist.go:347 +0x108
                                                                                    github.com/magodo/azlist/azlist.ListChildResource.func2()
                                                                                                                                                github.com/magodo/azlist@v0.0.0-20220923015326-17b16cc9b805/azlist/azlist.go:285 +0x4e
                                                                                   github.com/magodo/workerpool.(*workPool).Run.func1(0x1438c840)
                                                                                                                                                  github.com/magodo/workerpool@v0.0.0-20211124060943-1c48f3e5a514/workerpool.go:75 +0x8a
                                                                                     created by github.com/magodo/workerpool.(*workPool).Run
                                                                                                                                                github.com/magodo/workerpool@v0.0.0-20211124060943-1c48f3e5a514/workerpool.go:66 +0x51

The different type of resources in this RG, just in case there's any type not supported:

Type                                       
microsoft.alertsManagement/smartDetectorAlertRules
Microsoft.BotService/botServices
Microsoft.CognitiveServices/accounts
microsoft.insights/actiongroups
microsoft.insights/components
microsoft.insights/metricalerts
Microsoft.Logic/workflows
Microsoft.OperationalInsights/workspaces
Microsoft.SaaS/resources
Microsoft.Search/searchServices
Microsoft.Sql/servers
Microsoft.Sql/servers/databases
Microsoft.Storage/storageAccounts
Microsoft.Web/connections
Microsoft.Web/serverFarms
Microsoft.Web/sites

**Comment by farreciado** [comment]
Duplicates #257

**Comment by farreciado** [comment]
Duplicates #257
